### ISSUE TITLE
Possible tooltip bug

### ISSUE THREAD

**Issue by dt1973** [PMSI-AlignAlytics/dimple#157]
At http://jsbin.com/qezuvijuzu/1/edit -- if setting D's `x` to any number lower than 5, why do all entries receive an extra `x` in their hover tooltip?

**Comment by ParamountSoft** [comment]
The value for `x` and the legend in the tooltip having an additional interpretation of `x` are unrelated.

**Comment by dt1973** [comment]
Wait, I'm not sure I understand. So how do I get rid of that extra `x`?

**Comment by johnkiernander** [comment]
By including x in the series identifier and also on the x axis you are treating it as a measure (x axis) and a category (series identifier).  Therefore it's being associated with the data point as a string (unformatted, e.g. -2) and a number (formatted, e.g -2.0).  The tooltip will show any distinct values so to stop the double display you need to make them look the same.  The reason this only happens with values under 5 in your case is because over 5 the default format for the x axis will switch to 0dp.

You could do this a number of ways:  

1) Cut it off right at the source by adding a key to your data and disaggregating by that instead.  In your case there is already a key ("name"), so you don't need to include `x` in the series identifier at all: http://jsbin.com/haqula/4/edit?js,output

2) Make the x values in your data preformatted so that they appear the same way in both the x axis and the series: http://jsbin.com/zirubu/1/edit?js,output

3) Set the number format of the x axis to 0dp after drawing:http://jsbin.com/nosoto/1/edit?js,output

4) Write a custom tooltip: http://jsbin.com/pegeji/4/edit

Of these the first option is the simplest and the fourth is the most versatile.  2 and 3 are only really included to illustrate the cause.

**Comment by dt1973** [comment]
Thank you so much @johnkiernander for that amazing answer. Now I can go impress the hell out of my math class!
