### ISSUE TITLE
Text alignment in labels and legends

### ISSUE THREAD

**Issue by hxu** [PMSI-AlignAlytics/dimple#34]
I'm trying to recreate the grouped bar chart example [here](http://dimplejs.org/examples_viewer.html?id=bars_vertical_grouped), but am experiencing some positioning issues with the labels in certain parts of the chart:
- Legend labels appear offset above the legend keys: 
  ![image](https://f.cloud.github.com/assets/38583/1844526/6d02d36a-7534-11e3-9c66-dbd6c96b0f80.png).  The width of the label text is also not being taken into account when placing the next legend item.
- x and y axis labels are too close to the axis:
  ![image](https://f.cloud.github.com/assets/38583/1844528/8e53ec02-7534-11e3-85f1-fbcfc575f921.png) and 
  ![image](https://f.cloud.github.com/assets/38583/1844529/985c4d16-7534-11e3-8854-649eba256f92.png)

This looks like a styling issue, because when I remove Bootstrap's CSS styles, the chart renders fine.  However, I can't pinpoint which styles is affecting the placement of the text.  I've tried overriding the line spacing and text size, but that didn't seem to work.  The SVG is rendered in a variable width div, but the SVG itself has fixed width.

Can you shed some light on what assumptions dimple is using the calculate the positioning of the labels?

**Comment by falconair** [comment]
I ran into this issue as well. I had to set my project aside for a few weeks because I couldn't make head or tails of the situation. Luckily I just found the following comment by @johnkiernander on SO, which brought me here:
http://stackoverflow.com/a/22322570/46799

Looks like my problem is also caused by drawing to a non-visible div. In my case, I'm using bootstrap tabs. Chrome and Safari render my page just fine, Firefox shows an "NS_FAILURE_ERROR" in dimple.v2.1.0.js's line 1911. As mentioned by @hxu, this line contains 'this.getBBox()' method!

I can't use @twaggs solution, since I don't control BS tabs. If I come up with a solution, I'll post it here.
